services:
  safesplit-development:
    container_name: safesplit-development
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ../../.env
    restart: unless-stopped 