name: safesplit-development

networks:
  safesplit-network:
    driver: bridge

services:
  frontend:
    container_name: frontend-development
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
      - /app/node_modules
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
    networks:
      - safesplit-network

volumes:
  dfx_cache:
  dfx_config:
