"use client";

import { Copy, Shield } from "lucide-react";
import { Typography } from "@/components/ui/typography";

export default function PendingEscrowDetails({ transaction }: { transaction: any }) {
  const totalBTC = Array.isArray(transaction.to)
    ? transaction.to.reduce((sum: number, toEntry: any) => sum + Number(toEntry.amount), 0) / 1e8
    : 0;

  return (
    <>
      <Typography variant="large" className="text-[#FEB64D]">Funding required</Typography>

      <Typography variant="small" className="text-[#fff] font-semibold">
        Bitcoin deposit address
      </Typography>
      <div className="grid grid-cols-12 gap-3 mt-2">
        <div className="container-gray col-span-11">
          bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh
        </div>
        <div className="container-gray">
          <Copy />
        </div>
      </div>

      <div className="container-primary mt-4">
        <Typography variant="p" className="text-[#FEB64D] font-semibold">
          Send exactly {totalBTC.toFixed(8)} BTC to activate escrow
        </Typography>
        <Typography variant="p" className="text-white">
          This address is generated by ICP threshold ECDSA — no bridges, no wrap
        </Typography>
      </div>

      <div className="container-gray mt-6">
        <div className="flex items-start gap-3">
          <span className="bg-[#4F3F27] p-2 rounded-full">
            <Shield color="#FEB64D" />
          </span>
          <div>
            <Typography variant="base" className="text-white font-semibold">
              Fully Trustless
            </Typography>
            <Typography className="text-[#9F9F9F] mt-1">
              Escrow powered by Internet Computer's native Bitcoin integration. No bridge. No wrap. Fully trustless.
            </Typography>
          </div>
        </div>
      </div>
    </>
  );
}