services:
  splitsafe-local:
    container_name: splitsafe-local
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
      - /app/node_modules
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development 