services:
  splitsafe-local:
    container_name: splitsafe-local
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - ../../frontend/.env
    environment:
      - NODE_ENV=development 