services:
  safesplit-services:
    container_name: safesplit-services
    build:
      context: ../..
      dockerfile: docker/local/Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
      - /app/node_modules
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development 