"use client";

import { Copy, Shield } from "lucide-react";
import { Typography } from "@/components/ui/typography";
import { TransactionStats } from "@/components/ui/transaction-stats";

type ToEntry = {
  principal: string;
  name: string;
  amount: bigint;
  status: { [key: string]: null }; // e.g., { approved: null } or { pending: null }
};

type EscrowTransaction = {
  id: string;
  from: string;
  to: ToEntry[];
  status: "pending" | "confirmed" | "released";
  timestamp: bigint;
  title: string;
  depositAddress?: string;
  isRead?: boolean;
  releasedAt?: bigint;
};

export default function PendingEscrowDetails({ transaction }: { transaction: EscrowTransaction }) {
  const depositAddress = transaction?.depositAddress ||
    Array.from({ length: 42 }, () => Math.floor(Math.random() * 16).toString(16)).join("");

  const totalBTC =
    Array.isArray(transaction?.to) && transaction.to.length > 0
      ? transaction.to.reduce((sum, toEntry) => sum + Number(toEntry.amount), 0) / 1e8
      : 0;

  const recipientCount = transaction?.to?.length || 0;

  return (
    <>
      <TransactionStats 
        totalBTC={totalBTC}
        recipientCount={recipientCount}
        status={transaction.status}
      />

      <hr className="my-10 text-[#424444] h-[1px]" />

      <Typography variant="large" className="text-[#FEB64D]">Funding required</Typography>

      <Typography variant="small" className="text-[#fff] font-semibold">
        Bitcoin deposit address
      </Typography>
      <div className="grid grid-cols-12 gap-3 mt-2">
        <div className="container-gray col-span-11 break-all">
          {depositAddress}
        </div>
        <div className="container-gray cursor-pointer">
          <Copy />
        </div>
      </div>

      <div className="container-primary mt-4">
        <Typography variant="p" className="text-[#FEB64D] font-semibold">
          Send exactly {totalBTC.toFixed(8)} BTC to activate escrow
        </Typography>
        <Typography variant="p" className="text-white">
          This address is generated by ICP threshold ECDSA — no bridges, no wrap
        </Typography>
      </div>

      <div className="container-gray mt-6">
        <div className="flex items-start gap-3">
          <span className="bg-[#4F3F27] p-2 rounded-full">
            <Shield color="#FEB64D" />
          </span>
          <div>
            <Typography variant="base" className="text-white font-semibold">
              Fully Trustless
            </Typography>
            <Typography className="text-[#9F9F9F] mt-1">
              Escrow powered by Internet Computer&apos;s native Bitcoin integration.
              No bridge. No wrap. Fully trustless.
            </Typography>
          </div>
        </div>
      </div>
    </>
  );
}
