services:
  safesplit-staging:
    container_name: safesplit-staging
    build:
      context: ../..
      dockerfile: docker/stage/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - ../../.env
    restart: unless-stopped 